[package]
name    = "kiss3d"
version = "0.1.2"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

description = "3D graphics engine for Rust."
repository = "https://github.com/sebcrozet/kiss3d"
readme = "README.md"
keywords = [ "3D", "graphics", "OpenGL", "KISS" ]
license = "BSD-3-Clause"

include = [
    "src/**/*.rs",
    "examples/**/*.rs",
    "examples/media",
    "examples/Cargo.toml",
    "Cargo.toml",
    "LICENSE",
    "Readme.md"
]

[lib]
name = "kiss3d"
path = "src/lib.rs"

[dependencies]
nalgebra = "*"
gl = "*"
time = "*"
num = "*"
libc = "*"
ncollide_procedural = "*"
glfw = "*"
freetype-rs = "*"
image = "*"
